### ISSUE TITLE
Whitelisting and optional attributes

### ISSUE THREAD

**Issue by tivac** [birjj/svglint#74]
I'm working on a rule to ensure that all our SVGs match our target environment's SVG capabilities, and I'd like to create an `attr` rule that says:

> For `rule::selector` elements, any of the following attributes are valid but no others

Setting `rule::whitelist` looks like what I'd want but I can't actually use it in this case because any it requires that *every* configured attribute be defined on *all* matching elements. There's no way to define an optional attribute when the whitelist is enabled.

I don't really know what that should look like, since attribute selectors can already be `boolean|String|RegExp|Array<String>|Array<RegExp>`. Maybe if the attribute name ends with `?` it's optional?

```json5
{
  "rule::selector" : "svg mask",
  "rule::whitelist" : true,

  // All these elements have to exist on all matching elements
  "id" : true,
  "x" : true,
  "y" : true,

  // This attribute doesn't *have* to exist on the element, but it can
  "maskContentUnits?" : true

  // No other attributes are allowed on the element, because of rule::whitelist setting above
}
```

The results of the config above would be

```xml
<!-- Passes -->
<mask id="a" x="0" y="0">...</mask>
<mask id="a" x="0" y="0" maskContentUnits="userSpaceOnUse">...</mask>

<!-- Fails -->
<mask id="a">...</mask>
<mask id="a" x="0" y="0" width="100">...</mask>
```

Assuming we can come to an agreement on the config syntax I'd be happy to submit a PR for this feature <3

**Comment by ericcornelissen** [comment]
It does indeed seem _optional_ attributes aren't currently supported and I 100% agree it's a sensible thing to support. I agree the `?`-suffix is a suitable solution. as far as I can tell it's invalid in XML, and that seems to be respected by all parsers I tried.

Happy to review a Pull Request if you submit one, I'll assign you to this issue to make it clear you intent on working on it 🙂
