### ISSUE TITLE
Support SVGs directly from the CLI

### ISSUE THREAD

**Issue by PaulRBerg** [birjj/svglint#81]
I would like to be able to pass SVGs as direct command-line arguments to `svglint`, i.e. not have to provide a path to a file where the SVG content is located.

**Comment by ericcornelissen** [comment]
Sounds like a not unreasonable request. However, can you elaborate on what you're trying to do/achieve? There might be an alternative approach that's already supported, e.g. using the JS API.

**Comment by PaulRBerg** [comment]
Thanks for the quick answer!

My use case is pretty far-fetched from the JS ecosystem - I'm a Solidity developer, and I've built something similar to Uniswap's [`NFTSVG`](https://github.com/Uniswap/v3-periphery/blob/6cce88e63e176af1ddb6cc56e029110289622317/contracts/libraries/NFTSVG.sol).

I want to fuzz test the generated SVG and one of the tests is running `svglint` from the command line using [Foundry](https://github.com/foundry-rs/foundry)'s [`ffi`](https://book.getfoundry.sh/cheatcodes/ffi) feature. To do this now I have to create a file first, which is quite a pain since I have to do it from within Solidity.

**Comment by ericcornelissen** [comment]
Thanks for elaborating @PaulRBerg!

I'm wondering if supporting piping in(/providing) the SVG through [`stdin`](https://nodejs.org/api/process.html#processstdin) would work for you as well. Based on what you described I think it would.

I'm not sure yet whether a CLI argument or `stdin` makes more sense, but I'm leaning towards adding `stdin` support at the moment.
